const actionTypes = {
  FORM: {
    RESET_STATE: 'FORM.RESET_STATE',
    SET_FIELD: 'FORM.SET_FIELD',
  },
  FETCH_DATA: {
    RESET_STATE: 'RESET_STATE',
    REQUEST: 'REQUEST',
    SUCCESS: 'SUCCESS',
    FAILURE: 'FAILURE',
  },
  ME: {
    RESET_STATE: 'ME.RESET_STATE',
    SET_DATA: 'ME.SET_DATA',
    CHECK_AUTH: {
      REQUEST: 'ME.CHECK_AUTH_REQUEST',
      SUCCESS: 'ME.CHECK_AUTH_SUCCESS',
      FAILURE: 'ME.CHECK_AUTH_FAILURE',
    },
    SUBSCRIBE_TO_EMAIL_LIST: {
      REQUEST: 'ME.SUBSCRIBE_TO_EMAIL_LIST_REQUEST',
      SUCCESS: 'ME.SUBSCRIBE_TO_EMAIL_LIST_SUCCESS',
      FAILURE: 'ME.SUBSCRIBE_TO_EMAIL_LIST_FAILURE',
    },
  },
  LOGIN: {
    RESET_STATE: 'LOGIN.RESET_STATE',
    BASIC_LOGIN: {
      REQUEST: 'LOGIN.BASIC_LOGIN_REQUEST',
      SUCCESS: 'LOGIN.BASIC_LOGIN_SUCCESS',
      FAILURE: 'LOGIN.BASIC_LOGIN_FAILURE',
    },
  },
  SIGNUP: {
    RESET_STATE: 'SIGNUP.RESET_STATE',
    CREATE_ACCOUNT: {
      REQUEST: 'SIGNUP.CREATE_ACCOUNT_REQUEST',
      SUCCESS: 'SIGNUP.CREATE_ACCOUNT_SUCCESS',
      FAILURE: 'SIGNUP.CREATE_ACCOUNT_FAILURE',
    },
  },
  MAGAZINES: {
    RESET_STATE: 'MAGAZINES.RESET_STATE',
    //SET_LIST: 'MAGAZINES.SET_LIST',
    //FETCH_DATA: {
    //  REQUEST: 'MAGAZINES.FETCH_DATA_REQUEST',
    //  SUCCESS: 'MAGAZINES.FETCH_DATA_SUCCESS',
    //  FAILURE: 'MAGAZINES.FETCH_DATA_FAILURE',
    //},
  },
};

const namespaces = Object.keys(actionTypes).reduce((acc, type) => ({ ...acc, [type]: type }), {});

export { actionTypes as default, namespaces };
